include_guard(GLOBAL)

set(ANQST_QT_MAJOR_VERSION "5" CACHE STRING "Qt major version used by AnQst (5 or 6)")
set_property(CACHE ANQST_QT_MAJOR_VERSION PROPERTY STRINGS 5 6)

set(ANQST_QT_KNOWN_COMPONENTS Core Widgets Network WebChannel WebEngineWidgets Test UiPlugin)

function(anqst_get_qt_target_major_version out_var target_name)
    if(NOT TARGET "${target_name}")
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()

    set(resolved_target "${target_name}")
    get_target_property(aliased_target "${resolved_target}" ALIASED_TARGET)
    if(aliased_target)
        set(resolved_target "${aliased_target}")
    endif()

    get_target_property(target_qt_major "${resolved_target}" INTERFACE_QT_MAJOR_VERSION)
    if(target_qt_major MATCHES "^[56]$")
        set(${out_var} "${target_qt_major}" PARENT_SCOPE)
        return()
    endif()

    if(resolved_target MATCHES "^Qt([56])(::|$)")
        set(${out_var} "${CMAKE_MATCH_1}" PARENT_SCOPE)
        return()
    endif()

    set(${out_var} "" PARENT_SCOPE)
endfunction()

function(anqst_detect_qt_major_version out_var)
    set(alias_qt_major "")
    foreach(alias_target IN ITEMS Qt Qt::Core)
        anqst_get_qt_target_major_version(detected_alias_major "${alias_target}")
        if(detected_alias_major)
            set(alias_qt_major "${detected_alias_major}")
            break()
        endif()
    endforeach()

    set(has_qt5_target OFF)
    set(has_qt6_target OFF)
    foreach(component IN LISTS ANQST_QT_KNOWN_COMPONENTS)
        if(TARGET "Qt5::${component}")
            set(has_qt5_target ON)
        endif()
        if(TARGET "Qt6::${component}")
            set(has_qt6_target ON)
        endif()
    endforeach()

    if(alias_qt_major)
        set(resolved_qt_major "${alias_qt_major}")
    elseif(has_qt5_target AND has_qt6_target)
        message(FATAL_ERROR "Both Qt5 and Qt6 targets already exist in this CMake graph. Define a Qt or Qt::Core alias that selects one Qt major version before adding AnQst, or configure AnQst before mixing Qt majors.")
    elseif(has_qt6_target)
        set(resolved_qt_major "6")
    elseif(has_qt5_target)
        set(resolved_qt_major "5")
    else()
        set(resolved_qt_major "${ANQST_QT_MAJOR_VERSION}")
    endif()

    if(NOT resolved_qt_major MATCHES "^[56]$")
        message(FATAL_ERROR "ANQST_QT_MAJOR_VERSION must be 5 or 6, got '${resolved_qt_major}'.")
    endif()

    set(ANQST_QT_MAJOR_VERSION "${resolved_qt_major}" CACHE STRING "Qt major version used by AnQst (5 or 6)" FORCE)
    set(${out_var} "${resolved_qt_major}" PARENT_SCOPE)
endfunction()

function(anqst_find_qt_components)
    anqst_detect_qt_major_version(resolved_qt_major)
    find_package(Qt${resolved_qt_major} REQUIRED COMPONENTS ${ARGN})
    set(ANQST_QT_MAJOR_VERSION "${resolved_qt_major}" PARENT_SCOPE)
endfunction()
