// Built by AnQst 94b2aeb_dirty_build_6
#include <QtUiPlugin/QDesignerCustomWidgetInterface>
#include <QIcon>
#include <QObject>
#include <QString>
#include <QWidget>
#include "include/CdEntryEditor.h"

class CdEntryEditorDesignerPlugin final : public QObject, public QDesignerCustomWidgetInterface {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID "org.qt-project.Qt.QDesignerCustomWidgetInterface")
    Q_INTERFACES(QDesignerCustomWidgetInterface)

public:
    explicit CdEntryEditorDesignerPlugin(QObject* parent = nullptr) : QObject(parent) {}

    QString name() const override { return QStringLiteral("CdEntryEditor::CdEntryEditor"); }
    QString group() const override { return QStringLiteral("AnQst Widgets"); }
    QIcon icon() const override { return QIcon(QStringLiteral(":/anqstdesignerplugin/plugin-icon.png")); }
    QString toolTip() const override { return QStringLiteral("CdEntryEditor generated by AnQst."); }
    QString whatsThis() const override { return QStringLiteral("CdEntryEditor generated by AnQst."); }
    bool isContainer() const override { return false; }
    QString includeFile() const override { return QStringLiteral("include/CdEntryEditor.h"); }
    QWidget* createWidget(QWidget* parent) override {
        auto* widget = new CdEntryEditor::CdEntryEditor(parent);
        widget->setProperty("anqstDesignerContext", true);
        return widget;
    }
    bool isInitialized() const override { return true; }
    void initialize(QDesignerFormEditorInterface*) override {}

    QString domXml() const override {
        return QStringLiteral(
            "<ui language=\"c++\">\n"
            "  <widget class=\"CdEntryEditor::CdEntryEditor\" name=\"cdentryeditor\">\n"
            "  </widget>\n"
            "</ui>\n");
    }
};

#include "CdEntryEditorDesignerPlugin.moc"
